webproject/urls.py
from zooproject import views
"""webproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin,auth
from django.contrib.auth import views as auth_views
from django.urls import path, include
from zooproject import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zooproject.urls')),
]

zooproject/urls.py
from django.urls import path, reverse
from . import views
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.urls import path, include


urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='registration/login.html',next_page='/home')),
    path('registration/register/', views.signup),
    path('list_data', views.list_data),
    path('home', views.home, name='home'),
    path('logout', views.logout, name='logout'),
    path('registration/register_veterinary', SignupVeterinaryView.as_view(), name='registration/register_veterinary'),
    path('registration/register_staff', SignupStaffView.as_view(), name='registration/register_staff'),
    path('registration/register_visitor', SignupVisitorView.as_view(), name='registration/register_visitor'),
    path('create_animal', CreateAnimalView.as_view(), name='create_animal'),
    path('animal_editor/<str:pk>/', views.updateAnimal, name='edit/edit_animal'),
    path('animal_editor/', views.list_animals, name='animal_editor'),
    path('animal_delete/<str:pk>/', views.deleteAnimal, name='delete/delete_animal'),
    path('create_zoo', CreateZooView.as_view(), name='create_zoo'),
    path('list_zoo/', views.list_zoos, name='list_zoo'),

]

urlpatterns += staticfiles_urlpatterns()

zooproject/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import AbstractUser


class WebUser(AbstractUser):
    is_veterinary = models.BooleanField(default=False)
    is_visitor = models.BooleanField(default=False)
    is_zoo_staff = models.BooleanField(default=False)


class Zoo(models.Model):
    zoo_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=60)
    description = models.TextField(blank=True, null=True)
    max_visitors = models.DecimalField('Max amount of visitors', max_digits=8, decimal_places=0, blank=False, null=False)
    address = models.CharField(max_length=80)
    postalcode = models.DecimalField('Postal code', max_digits=8, decimal_places=0, blank=False, null=False)

    def __str__(self):
        return str(self.name)


class Worker(models.Model):
    worker_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)
    age = models.IntegerField(null=False)
    address = models.CharField(max_length=80)
    postalcode = models.IntegerField(blank=False, null=False)
    zoo_id = models.ForeignKey(Zoo, null=True, on_delete=models.CASCADE)
    # ??? phone_number = PhoneNumberField(null=False, blank=False, unique=True) # from phonenumber_field.modelfields import PhoneNumberField # pip install django-phonenumber-field
    # ??? zoo_id = get id from Zoo class

    def __str__(self):
        return str(self.name)


class Staff(Worker):
    User = models.OneToOneField(WebUser, on_delete=models.CASCADE, primary_key=True)
    assigned_habitat = models.CharField(max_length=80, default="Dolphins")

    def __str__(self):
        return str(self.User)


class Veterinary(Worker):
    User = models.OneToOneField(WebUser, on_delete=models.CASCADE, primary_key=True)
    number_assigned_animals = models.IntegerField(null=False, blank=False)
    # name varchar(50)

    def __str__(self):
        return str(self.User)


class Animal(models.Model):
    animal_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)
    zoo_id = models.ForeignKey(Zoo, null=True, blank=True, on_delete=models.CASCADE)
    staff_id = models.ForeignKey(Staff, null=True, blank=True, on_delete=models.CASCADE)
    veterinary_id = models.ForeignKey(Veterinary, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


class Visitor(models.Model):
    User = models.OneToOneField(WebUser, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=40,blank=False,null=False)
    telephone = models.DecimalField(max_digits=9, decimal_places=0, blank=False,null=False)
    email = models.EmailField(blank=False,null=False)
    age = models.DecimalField(max_digits=3, decimal_places=0, blank=False,null=False)
    dateLatestVisit = models.DateField(default=date.today,blank=False,null=False)
    zoo_id = models.ForeignKey(Zoo, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.User)

zooproject/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db import transaction
from django.forms import ModelForm

from .models import *
import datetime


class VeterinarySignupForm(UserCreationForm):
    name = forms.CharField(max_length=40, widget=forms.TextInput, required=True)
    age = forms.IntegerField(required=True)
    address = forms.CharField(max_length=8, widget=forms.TextInput, required=True)
    postalcode = forms.IntegerField(required=True)
    zoo_id = forms.ModelChoiceField(queryset=Zoo.objects.all(), empty_label="(Nothing)")
    number_assigned_animals = forms.IntegerField(required=True)

    class Meta(UserCreationForm.Meta):
        model = WebUser

    @transaction.atomic
    def save(self):
        web_user = super().save(commit=False)
        web_user.is_veterinary = True
        web_user.save()
        zoo = Zoo.objects.get(zoo_id=self.data.get('zoo_id'))
        veterinary = Veterinary.objects.create(
            User=web_user, postalcode=self.data.get('postalcode'),
            zoo_id=zoo, number_assigned_animals= self.data.get('number_assigned_animals'),
            name=self.data.get('name'), address = self.data.get('address'),
            age=self.data.get('age'))
        veterinary.save()
        # client.CIF.add(*self.cleaned_data.get('CIF'))
        return web_user  # web_user


class StaffSignupForm(UserCreationForm):
    name = forms.CharField(max_length=40, widget=forms.TextInput, required=True)
    age = forms.IntegerField(required=True)
    address = forms.CharField(max_length=8, widget=forms.TextInput, required=True)
    postalcode = forms.IntegerField(required=True)
    zoo_id = forms.ModelChoiceField(queryset=Zoo.objects.all(), empty_label="(Nothing)")
    assigned_habitat = forms.CharField(max_length=80, widget=forms.TextInput, required=True)

    class Meta(UserCreationForm.Meta):
        model = WebUser

    @transaction.atomic
    def save(self):
        web_user = super().save(commit=False)
        web_user.is_zoo_staff = True
        web_user.save()
        zoo = Zoo.objects.get(zoo_id=self.data.get('zoo_id'))
        staff = Staff.objects.create(
            User=web_user, postalcode=self.data.get('postalcode'),
            zoo_id=zoo, assigned_habitat= self.data.get('assigned_habitat'),
            name=self.data.get('name'), address = self.data.get('address'),
            age=self.data.get('age'))
        staff.save()
        # client.CIF.add(*self.cleaned_data.get('CIF'))
        return web_user  # web_user


class CreateAnimalForm(ModelForm):
    class Meta:
        model = Animal
        #fields = '__all__'
        exclude = ['veterinary_id']


class CreateZooForm(ModelForm):
    class Meta:
        model = Zoo
        #fields = '__all__'
        exclude = ['admin_id']


class VisitorSignupForm(UserCreationForm):
    name = forms.CharField(max_length=40, widget=forms.TextInput, required=True)
    telephone = forms.IntegerField(required=True)
    email = forms.EmailField(required=True)
    age = forms.IntegerField(required=True)
    dateLatestVisit = forms.DateField(initial=datetime.date.today)
    zoo_id = forms.ModelChoiceField(queryset=Zoo.objects.all(), empty_label="(Nothing)")

    class Meta(UserCreationForm.Meta):
        model = WebUser

    @transaction.atomic
    def save(self):
        web_user = super().save(commit=False)
        web_user.is_visitor = True
        web_user.save()
        zoo = Zoo.objects.get(zoo_id=self.data.get('zoo_id'))
        visitor = Visitor.objects.create(
            User=web_user, telephone=self.data.get('telephone'), email= self.data.get('email'),
            age=self.data.get('age'), dateLatestVisit=self.data.get('dateLatestVisit'), zoo_id=zoo)
        visitor.save()
        # client.CIF.add(*self.cleaned_data.get('CIF'))
        return web_user  # web_user

class AnimalEditorForm(forms.ModelForm):
    class Meta:
        model = Animal
        exclude = ['animal_id']
'''

class PeticionStandClienteForm(forms.ModelForm):
    class Meta:
        model = PeticionStand
        exclude = ['clientUsername', 'gestorUsername', 'estado', 'revisado']


class PeticionStandGestorForm(forms.ModelForm):
    class Meta:
        model = PeticionStand
        exclude = ['gestorUsername']

'''

zooproject/views.py
# Create your views here.
from django.contrib.auth import login, authenticate, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView
from .models import *
from .forms import *
from django.views.generic.edit import CreateView, UpdateView



class SignupVeterinaryView(CreateView):
    model = WebUser
    form_class = VeterinarySignupForm
    template_name = 'registration/register_veterinary.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'veterinary'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        web_user = form.save()
        login(self.request, web_user)
        return redirect('/')


class SignupStaffView(CreateView):
    model = WebUser
    form_class = StaffSignupForm
    template_name = 'registration/register_staff.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'zoo_staff'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        web_user = form.save()
        login(self.request, web_user)
        return redirect('/')


class SignupVisitorView(CreateView):
    model = WebUser
    form_class = VisitorSignupForm
    template_name = 'registration/register_visitor.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'visitor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        web_user = form.save()
        login(self.request, web_user)
        return redirect('/')


class CreateAnimalView(CreateView):
    model = Animal
    form_class = CreateAnimalForm
    template_name = 'create_animal.html'

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_veterinary:
            return redirect('/')
        else:
            form = self.form_class
            template_name = 'create_animal.html'
            return render(request, template_name, {'form': form})

    def form_valid(self, form):
        if self.request.user.is_veterinary:
            veterinary = Veterinary.objects.get(User=self.request.user)
            form.instance.veterinary_id = veterinary
            form.save()
            return redirect('/')

        else:
            print("Error, user is not a veterinary")
            return redirect('/')



class CreateZooView(CreateView):
    model = Zoo
    form_class = CreateZooForm
    template_name = 'create_zoo.html'

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            return redirect('/')
        else:
            form = self.form_class
            template_name = 'create_zoo.html'
            return render(request, template_name, {'form': form})

    def form_valid(self, form):
        if self.request.user.is_superuser:
            admin = get_user_model()
            form.instance.Username = admin
            form.save()
            return redirect('/')
        else:
            print("Error, user is not an admin")
            return redirect('/')



def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def list_data(r):
    workers = Worker.objects.all()
    workers_dictionary =  {'workers': workers}
    
    return render(r, 'zooproject/list_data.html', workers_dictionary)


def list_animals(request):
    if request.user.is_veterinary:
        animals = Animal.objects.all()
        animals_dictionary = {'animals': animals}
        return render(request, 'zooproject/list_animals.html', animals_dictionary)
    else:
        print("Error el user no es un veterinario")
        return redirect('/')

def updateAnimal( request, *args, **kwargs):
    if request.user.is_veterinary:
        animal = Animal.objects.get(animal_id=kwargs.get('pk'))
        form = AnimalEditorForm(instance=animal)

        if request.method == 'POST':
            form = AnimalEditorForm(request.POST, instance=animal)
            form.instance.animal_id = kwargs.get('pk')
            if form.is_valid():
                edit_animal = Animal.objects.get(animal_id=kwargs.get('pk'))
                edit_animal.save()
                form.save()
                return redirect('/animal_editor')

        context = {'form': form}
        return render(request, 'edit/edit_animal.html', context)
    else:
        print("Error el user no es un veterinario")
        return redirect('/')

def deleteAnimal(request, pk):
    animal = Animal.objects.get(animal_id=pk)
    if request.user.is_veterinary:
        if request.method == 'POST':
            animal.delete()
            return redirect('/animal_editor')
        context = {'item':animal}
        return render(request, 'delete/delete_animal.html', context)
    else:
        print("Error el user no es un veterinario")
        return redirect('/')


def home(request):
    return render(request, 'home.html')


def logout(request):
    return redirect('/')


def list_zoos(request):
    zoos = Zoo.objects.all()
    zoos_dictionary = {'zoos': zoos}
    return render(request, 'zooproject/list_zoo.html', zoos_dictionary)

zooproject/templates/base.html
<!-- templates/base.html -->
{% load static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/login-custom.css' %}">
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<link rel="stylesheet" href="{% static 'css/shared.css' %}">
<link rel="stylesheet" href="{% static 'css/register.css' %}">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">
            Home
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'list_zoo' %}">
            Zoos
          </a>
        </li>

        {% if user.is_veterinary %}

        <li>
          <a class="nav-link active" aria-current="page" href="{% url 'create_animal' %}">  <!--Warning-->
            Create an animal
          </a>
        </li>
        <li>
          <a class="nav-link active" aria-current="page" href="{% url 'animal_editor' %}">  <!--Warning-->
            Delete and edit an animal
          </a>
        </li>
        {% endif %}

        {% if user.is_zoo_staff %}
        {% endif %}

        {% if user.is_superuser %}
        <li>
          <a class="nav-link active" aria-current="page" href="{% url 'create_zoo' %}">  <!--Warning-->
            Create Zoo
          </a>
        </li>
            <li>
          <a class="nav-link active" aria-current="page" href="{% url 'registration/register_veterinary' %}">  <!--Warning-->
            Register a Veterinary
          </a>
        </li>
            <li>
          <a class="nav-link active" aria-current="page" href="{% url 'registration/register_staff' %}">  <!--Warning-->
            Register a Staff
          </a>
        </li>
            <li>
          <a class="nav-link active" aria-current="page" href="{% url 'registration/register_visitor' %}">  <!--Warning-->
            Register a Visitor
          </a>
        </li>
        {% endif %}

      {% if user.is_visitor %}

      {% endif %}

      </ul>
      <span class="navbar-text">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          {% if user.is_authenticated %}

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">
                Logout
              </a>
            </li>
          {% endif %}

      </ul>
      </span>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}

zooproject/templates/create_animal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
      {% load static %}
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/api_animals.js' %}"></script>
</head>
<body>
{% include 'base.html' %}

{% block title %}

    <div>
        <h1 style="text-align:center">
            Create animal
        </h1>
    </div>
{% endblock title %}

{% block content %}
    <div>
        <form action = "" method = "post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value=Submit>
             <button type="button" id="trigger_api">Autocomplete with API</button>
        </form>
    </div>

{% endblock content %}

</body>
</html>

zooproject/templates/create_zoo.html
{% include 'base.html' %}
  {% load static %}
{% block title %}
    <div>
        <h1 class="page-head"style="text-align:center">
            Create Zoo
        </h1>
    </div>
{% endblock title %}

{% block content %}
    <body class="page-body">
        <center>
            <div>
                <form action = "" method = "post">
                    {% csrf_token %}
                    <table>
                        <tbody>
                            <tr>
                                <td><input style="width:472px" type="text" name="name" maxlength="60" required="" id="id_name" placeholder="Name"></td>
                            </tr>
                            <tr>
                                <td><textarea name="description" cols="40" rows="5" id="id_description" placeholder="Description"></textarea></td>
                            </tr>
                            <tr>
                                <td><input style="width:472px" type="number" name="max_visitors" step="1" required="" id="id_max_visitors" placeholder="Max amount of visitors"></td>
                            </tr>
                            <tr>
                                <td><input style="width:472px" type="text" name="address" maxlength="80" required="" id="id_address" placeholder="Address"></td>
                            </tr>
                            <tr>
                                <td><input style="width:472px" type="number" name="postalcode" step="1" required="" id="id_postalcode" placeholder="Postal code"></td>
                            </tr>
                            <tr>
                                <td style="padding-left:82%;"><input class="page-button" style="margin-top:25%;"  type="submit" value=Submit></td>
                            </tr>
                        </tbody>
                    </table>

                </form>
            </div>
        </center>
    </body>
{% endblock content %}

zooproject/templates/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $("#trigger_api").click(function () {
            console.log("Entra")
            var countries = ["Afghanistan", "Albania","Zaire", "Zambia", "Zimbabwe"];
                $('#id_name').val(countries[0]);
        });
    </script>
</head>
<body>
{% include 'base.html' %}
  {% load static %}
{% block title %}

    <div>
        <h1 style="text-align:center">
            Create animal
        </h1>
    </div>
{% endblock title %}

{% block content %}
    <div>
        <form action = "" method = "post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value=Submit">
             <button type="button" id="trigger_api">Autocomplete with API</button>
        </form>
    </div>
    </div>
{% endblock content %}

</body>
</html>

zooproject/templates/home.html
<!-- templates/home.html -->
{% include 'base.html' %}
  {% load static %}
{% block content %}
    <body class="page-body">
        <center>
            <div class="column">
                <h1 class="page-head">Welcome to our Zoo page</h1>
                <img class="home-logo" src="https://drive.google.com/uc?export=view&id=1a1a7FdEoU0jnAPiv05dk5koFLXsModAc">
            </div>
        </center>
    </body>
{% endblock content %}

zooproject/templates/register_animal.html
{% include 'base.html' %}
  {% load static %}
{% block title %}
    <div>
        <h1 style="text-align:center">
            Create animal
        </h1>
    </div>
{% endblock title %}

{% block content %}
    <div>
        <form action = "" method = "post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value=Submit">
        </form>
    </div>
    </div>
{% endblock content %}